---
#
# edX Configuration
#
# github:     https://github.com/openedx/configuration
# wiki:       https://github.com/openedx/configuration/wiki
# code style: https://github.com/openedx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/openedx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role hotg
# 
# Example:
#
# dependencies:
#   - {
#   role: my_role 
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }

dependencies:
  # Java dependency removed - Hotg now handles its own Java installation
  - supervisor
