#
# edX Configuration
#
# github:     https://github.com/openedx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/openedx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role newrelic_infrastructure
#

#
# vars are namespace with the module name.
#
---

# Any extra config you want to specify
#
# OS package
#

newrelic_infrastructure_debian_pkgs:
  - newrelic-infra

newrelic_infrastructure_redhat_pkgs:
  - newrelic-infra

