- name: Deploy edX Commerce Coordinator
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'commerce_coordinator'
    REGISTRAR_ENABLED: True
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_default_sites:
        - commerce_coordinator
    - commerce_coordinator
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: hermes
      HERMES_TARGET_SERVICE: 'commerce_coordinator'
      when: COMMERCE_COORDINATOR__HERMES_ENABLED
