- name: Deploy edX designer
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'designer'
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_default_sites:
        - designer
    - designer
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: hermes
      HERMES_TARGET_SERVICE: 'designer'
      when: DESIGNER_HERMES_ENABLED
