- name: Build cloud devstack AMI
  hosts: all
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
      become: True
    - role: aws_devstack
