- name: Deploy discussions MFE Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'discussions'
    MYMFE_ENABLED: True
    MYMFE_SANDBOX_BUILD: False
  roles:
    - role: mfe
      MFE_NAME: discussions
      MFE_VERSION: '{{ DISCUSSIONS_MFE_VERSION }}'
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE