- name: Deploy edX License Manager
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'license_manager'
    REGISTRAR_ENABLED: True
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_default_sites:
        - license_manager
    - license_manager
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: hermes
      HERMES_TARGET_SERVICE: 'license_manager'
      when: REGISTRAR_HERMES_ENABLED
