---
# Build a kibana/logstash/elasticsearch server for capturing and
# analyzing logs.
- name: Configure syslog server
  hosts: all
  become: True
  roles:
    - common
    - openjdk
    - elasticsearch
    - logstash
    - kibana
    - role: nginx
      nginx_sites:
        - kibana
