- name: Deploy xqueue
  hosts: all
  become: True
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: automated
      AUTOMATED_USERS: "{{ XQUEUE_AUTOMATED_USERS | default({}) }}"
    - role: nginx
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
    - role: hermes
      HERMES_TARGET_SERVICE: 'xqueue'
      when: XQUEUE_HERMES_ENABLED
