---
#
# edX Configuration
#
# github:     https://github.com/openedx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/openedx/configuration/blob/master/LICENSE.TXT
#
# Tasks for role analytics_api
#
# Overview: Most of this role's tasks come from edx_django_service.
#
#
# Dependencies:
#

- name: create api users
  shell: "{{ analytics_api_home }}/venvs/{{ analytics_api_service_name }}/bin/python manage.py set_api_key {{ item.key }} {{ item.value }}"
  args:
    chdir: "{{ analytics_api_code_dir }}"
  become_user: "{{ analytics_api_user }}"
  environment: "{{ analytics_api_environment }}"
  with_dict: "{{ ANALYTICS_API_USERS }}"
  tags:
    - manage
    - manage:app-users

- name: install python3.11
  apt:
    pkg:
      - python3.11-dev
      - python3.11-distutils
    update_cache: yes
  register: install_pkgs
  until: install_pkgs is success
  retries: 10
  delay: 5
  when: edx_django_service_use_python311
  tags:
    - install
    - install:system-requirements

- name: build virtualenv with python3.11
  command: "virtualenv --python=python3.11 {{ edx_django_service_venv_dir }}"
  args:
    creates: "{{ edx_django_service_venv_dir }}/bin/pip"
  become_user: "{{ edx_django_service_user }}"
  when: edx_django_service_use_python311
  tags:
    - install
    - install:system-requirements
