---
#
# edX Configuration
#
# github:     https://github.com/openedx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/openedx/configuration/blob/master/LICENSE.TXT
#
# Tasks for role analytics_api
#
# Overview: Most of this role's tasks come from edx_django_service.
#
#
# Dependencies:
#

- name: install python3.11
  when: not use_vendored_py311
  apt:
    pkg:
      - python3.11-dev
      - python3.11-distutils
    update_cache: yes
  register: install_pkgs
  until: install_pkgs is success
  retries: 10
  delay: 5
  tags:
    - install
    - install:system-requirements

- name: "Directory for vendored Python 3.11 packages"
  when: use_vendored_py311
  file:
    path: "/tmp/vendored_python_{{ vendored_py311_build }}"
    state: directory
  tags:
    - install
    - install:system-requirements

- name: "Download vendored Python 3.11 packages"
  when: use_vendored_py311
  get_url:
    url: "{{ vendored_py311_url_base }}/{{ item|urlencode }}"
    dest: "/tmp/vendored_python_{{ vendored_py311_build }}/{{ item }}"
    timeout: 60
  with_items: "{{ vendored_py311_pkgs }}"
  tags:
    - install
    - install:system-requirements

- name: "Install dependencies for Python 3.11"
  when: use_vendored_py311
  apt:
    pkg: "{{ py311_dependencies }}"
    update_cache: yes
  tags:
    - install
    - install:system-requirements

- name: "Install vendored Python 3.11 packages"
  when: use_vendored_py311
  command: dpkg -i "/tmp/vendored_python_{{ vendored_py311_build }}/{{ item }}"
  with_items: "{{ vendored_py311_pkgs }}"
  tags:
    - install
    - install:system-requirements

- name: create api users
  shell: "{{ analytics_api_home }}/venvs/{{ analytics_api_service_name }}/bin/python manage.py set_api_key {{ item.key }} {{ item.value }}"
  args:
    chdir: "{{ analytics_api_code_dir }}"
  become_user: "{{ analytics_api_user }}"
  environment: "{{ analytics_api_environment }}"
  with_dict: "{{ ANALYTICS_API_USERS }}"
  tags:
    - manage
    - manage:app-users
